version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Images"
          command: sh ./build-images.sh
      - ejecute:
          name: "Run Docker Images"
          command: docker run cibuilds/docker
