version: 2.1

workflows:
  main:
    jobs:
      - build:
          context: ContextoSeguro

jobs:
  build:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Images"
          command: |
            echo "export BOTNAME=$BOTNAME" >> $BASH_ENV
            echo "export BOTPASSWD=$BOTPASSWD" >> $BASH_ENV
            sh ./build-images.sh
