version: 2.1

workflows:
  main:
    triggers:
      - schedule:
          cron: "20 11 * * *"

    jobs:
      - build:
          context: ContextoSeguro

jobs:
  build:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Images"
          command: sh ./build-images.sh
