name: Build and test of Python Script
 
on: [push]
 
jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Building the image from the Dockerfile
        uses: ./.github/action-docker