name: Build and test of Python Script
 
on:
  schedule:
    - cron: '* * * * *'
 
jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Building the image from the Dockerfile
        uses: ./.github/action-docker
        env:
          BOTNAME: ${​​​​​{​​​​​ secrets.BOTNAME }​​​​​}​​​​​
          BOTPASSWD: ${{ secrets.BOTPASSWD }}
